Update pt.json
vtex-apps/b2b-quotes pull request #15
Opened 2022-05-12 16:59 UTC by adberaldo

Update translation PT-BR

#### What problem is this solving?Complete PT-BR translations

#### How to test it?
Navigate the app to check messages

[Workspace](Link goes here!)

#### Screenshots or example usage:

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2022-05-13 14:37 UTC, arturmagalhaesjr requested changes

2022-05-13 14:37 UTC, arturmagalhaesjr commented on messages/pt.json
> +  "store/b2b-quotes.quotes-table.filters.none": "Nada",
It could be "Nenhum" instead of "Nada"

2022-05-13 14:37 UTC, arturmagalhaesjr commented on messages/pt.json
> +  "store/b2b-quotes.quote-details.submit-to-sales-rep": "Enviar ao Vendedor",
"Representante de Vendas"

2022-05-13 14:37 UTC, arturmagalhaesjr commented on messages/pt.json
> +  "store/b2b-quotes.quote-details.items.refId.title": "Cód.Refer.",
"Código Ref "

2024-09-02 17:07 UTC, enzomerca commented
This is an old PR and these translations are already fixed on `master`

2024-09-02 17:07 UTC, closed without merging