B2BQUOTES-24
vtex-apps/b2b-quotes pull request #3
Opened 2022-02-15 14:45 UTC by arturmagalhaesjr

- Improvement of Quote Details,
- Calculate the discount against original price (listPrice item)
- If user input some value above from max discount, it's blocked to save, and an alert is shown.

#### What problem is this solving?

- store the original price
- always discount against original price for the discount limi: Use case: if an order is adjusted multiple times and a 30% discount is applied each time
- always display original price
- need to always run discount validation at the item level

#### How to test it?

Go to B2B Quotes:
[https://artur3--b2bstoreqa.myvtex.com/b2b-quotes](https://artur3--b2bstoreqa.myvtex.com/b2b-quotes)

Sales Rep user:
artur.magalhaes@vtex.com.br / Vtex1234

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/5812946/154085038-3624c40e-4854-4aab-8df4-7450535103fa.png)

2022-02-22 16:27 UTC, polishq requested changes
Functionality looks good but I think some of the messaging could be improved.

In the totalizers at the top of the quote, currently we have `Subtotal` and `Total`. Let's change that to `Original Subtotal` and `Quoted Subtotal`. This is because, in both cases, the amount shown on this page does not yet include shipping or tax.

Additionally, I think it would help to add column header labels to the quote items table. Currently the difference between the two prices is not clear. The labels could be `Original Price` and `Quoted Price` (the other columns will need labels like Image, Name, Quantity, etc). Also, maybe if the original price is different from the quoted price, we can put a strikethrough on the original price.

2022-02-23 00:18 UTC, arturmagalhaesjr reviewed
Done

2022-02-23 14:13 UTC, polishq requested changes

2022-02-23 14:13 UTC, polishq commented on messages/context.json
> +  "store/b2b-quotes.quote-details.quote-price.title": "Quote Price",
```suggestion
  "store/b2b-quotes.quote-details.quote-price.title": "Quoted Price",
```

2022-02-23 14:13 UTC, polishq commented on messages/en.json
> +  "store/b2b-quotes.quote-details.quote-price.title": "Quote Price",
```suggestion
  "store/b2b-quotes.quote-details.quote-price.title": "Quoted Price",
```

2022-02-23 14:13 UTC, polishq commented on messages/es.json
> +  "store/b2b-quotes.quote-details.quote-price.title": "Quote Price",
```suggestion
  "store/b2b-quotes.quote-details.quote-price.title": "Quoted Price",
```

2022-02-23 14:13 UTC, polishq commented on messages/pt.json
> +  "store/b2b-quotes.quote-details.quote-price.title": "Quote Price",
```suggestion
  "store/b2b-quotes.quote-details.quote-price.title": "Quoted Price",
```

2022-02-23 14:13 UTC, polishq commented on messages/ro.json
> +  "store/b2b-quotes.quote-details.quote-price.title": "Quote Price",
```suggestion
  "store/b2b-quotes.quote-details.quote-price.title": "Quoted Price",
```

2022-02-23 14:13 UTC, polishq commented on react/components/QuoteDetails.tsx
> +                                      : null
This is resulting in "null" being written into the class attribute.
```suggestion
                                      : ''
```

2022-02-23 14:49 UTC, arturmagalhaesjr reviewed
done

2022-02-23 15:24 UTC, polishq approved these changes

2022-02-23 15:57 UTC, merged