Feat/new splitting quote
vtex-apps/b2b-quotes pull request #66
Opened 2024-11-27 14:22 UTC by josmartrigueiro

#### What problem is this solving?
Add new splitting quote configuration to settings UI

#### How to test it?
1. access admin
2. go to the B2B quote flow

[[Workspace](Link goes here!)](https://josmarsoares--b2bstore005.myvtex.com/admin/b2b-quotes/settings)

#### Screenshots or example usage:
<img width="1440" alt="Screenshot 2024-11-27 at 11 19 45" src="https://github.com/user-attachments/assets/4f21c151-25e3-463e-93dd-fa922e31b0a0">

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2024-12-17 19:17 UTC, Matheus-Aguilar commented on messages/bg.json
> +  "admin/b2b-quotes.settings.saveSettings.management.quotes.experiration.data": "Expiration Period for Quotes and Saved Carts",
There's a typo in the property name. It is written `experiration` and should be `expiration`. The same issue is present in the messages in other languages. Also, this property text is in English in all languages and not translated.

2024-12-17 19:18 UTC, Matheus-Aguilar commented on react/components/AppSettings.tsx
> +              Expiration Period for Quotes and Saved Carts
This section has a hardcoded text instead of a `FormattedMessage`. Why?

2025-01-06 17:30 UTC, Josmar-jr commented on messages/bg.json
> +  "admin/b2b-quotes.settings.saveSettings.management.quotes.experiration.data": "Expiration Period for Quotes and Saved Carts",
@Matheus-Aguilar corrected

2025-01-06 17:32 UTC, Josmar-jr commented on react/components/AppSettings.tsx
> +              Expiration Period for Quotes and Saved Carts
corrected

2025-01-13 16:30 UTC, tiago-freire requested changes

2025-01-13 16:30 UTC, tiago-freire commented on react/components/AppSettings.tsx
> +              aaaa
@Josmar-jr ficou esse "aaaa" aqui

2025-01-20 14:36 UTC, ArthurTriis1 submitted a review, later dismissed

2025-01-20 16:34 UTC, ArthurTriis1 approved these changes

2025-01-21 13:42 UTC, merged